// ignore_for_file: avoid_print
// Verification script: runs Dart implementations against golden data and
// reports maximum differences for each module.
//
// Usage: dart run tool/verify_parity.dart
//
// This is NOT a test — it's a diagnostic tool to verify that the Dart
// implementations actually produce the same values as the C++ Framework
// (golden data was generated by C++ Framework execution).

import 'dart:convert';
import 'dart:ffi';
import 'dart:io';
import 'dart:math' as math;
import 'dart:typed_data';

import 'package:l2d_flutter_plugin/src/generated/cubism_core_bindings.dart';
import 'package:l2d_flutter_plugin/src/core/native_library.dart';
import 'package:l2d_flutter_plugin/src/core/cubism_moc.dart';
import 'package:l2d_flutter_plugin/src/core/cubism_model.dart';
import 'package:l2d_flutter_plugin/src/framework/math/cubism_math.dart';
import 'package:l2d_flutter_plugin/src/framework/math/libm.dart';
import 'package:l2d_flutter_plugin/src/framework/math/cubism_matrix44.dart';
import 'package:l2d_flutter_plugin/src/framework/math/cubism_vector2.dart';
import 'package:l2d_flutter_plugin/src/framework/math/float32.dart';
import 'package:l2d_flutter_plugin/src/framework/cubism_model_setting_json.dart';
import 'package:l2d_flutter_plugin/src/framework/motion/cubism_motion.dart';
import 'package:l2d_flutter_plugin/src/framework/motion/cubism_motion_manager.dart';
import 'package:l2d_flutter_plugin/src/framework/motion/cubism_expression_motion.dart';
import 'package:l2d_flutter_plugin/src/framework/physics/cubism_physics.dart';
import 'package:l2d_flutter_plugin/src/framework/effect/cubism_pose.dart';

class Diff {
  double maxAbs = 0.0;
  double maxRel = 0.0;
  int total = 0;
  int over1e6 = 0;
  int over1e4 = 0;
  int over1e2 = 0;
  String maxAbsLocation = '';

  void record(double expected, double actual, String location) {
    total++;
    final absDiff = (expected - actual).abs();
    final scale = math.max(expected.abs(), actual.abs());
    final relDiff = scale > 0 ? absDiff / scale : 0.0;
    if (absDiff > maxAbs) {
      maxAbs = absDiff;
      maxAbsLocation = location;
    }
    if (relDiff > maxRel) maxRel = relDiff;
    if (absDiff > 1e-6) over1e6++;
    if (absDiff > 1e-4) over1e4++;
    if (absDiff > 1e-2) over1e2++;
  }

  String summary() => 'samples=$total maxAbs=${maxAbs.toStringAsExponential(3)} '
      'over1e-6=$over1e6 over1e-4=$over1e4 over1e-2=$over1e2 '
      '(at $maxAbsLocation)';
}

Map<String, dynamic> _loadGolden(String name) {
  final path = '${Directory.current.path}/test/golden/$name';
  return jsonDecode(File(path).readAsStringSync()) as Map<String, dynamic>;
}

void _section(String title) {
  print('');
  print('═══════════════════════════════════════════════════════════');
  print('  $title');
  print('═══════════════════════════════════════════════════════════');
}

// ---------------------------------------------------------------------------
// MATH
// ---------------------------------------------------------------------------
void verifyMath() {
  _section('CubismMath');
  final g = _loadGolden('math_golden.json');

  // easingSine
  final diff = Diff();
  for (final e in (g['easingSine'] as List).cast<Map<String, dynamic>>()) {
    final t = (e['t'] as num).toDouble();
    final expected = (e['v'] as num).toDouble();
    final actual = CubismMath.getEasingSine(t);
    diff.record(expected, actual, 't=$t');
  }
  print('  easingSine: ${diff.summary()}');

  // Cardano
  final diff2 = Diff();
  for (final c in (g['bezier'] as List).cast<Map<String, dynamic>>()) {
    final a = (c['a'] as num).toDouble();
    final b = (c['b'] as num).toDouble();
    final cc = (c['c'] as num).toDouble();
    final d = (c['d'] as num).toDouble();
    final expected = (c['result'] as num).toDouble();
    final actual = CubismMath.cardanoAlgorithmForBezier(a, b, cc, d);
    diff2.record(expected, actual, 'a=$a,b=$b,c=$cc,d=$d');
  }
  print('  cardanoAlgorithmForBezier: ${diff2.summary()}');

  // Matrix multiply
  final diff3 = Diff();
  for (final c in (g['matrixMultiply'] as List).cast<Map<String, dynamic>>()) {
    final a = Float32List.fromList(
        (c['a'] as List).map((e) => (e as num).toDouble()).toList());
    final b = Float32List.fromList(
        (c['b'] as List).map((e) => (e as num).toDouble()).toList());
    final expected = (c['result'] as List).map((e) => (e as num).toDouble()).toList();
    final dst = Float32List(16);
    CubismMatrix44.multiply(a, b, dst);
    for (int i = 0; i < 16; i++) {
      diff3.record(expected[i], dst[i], 'idx=$i');
    }
  }
  print('  matrixMultiply: ${diff3.summary()}');

  // Matrix inverse
  final diff4 = Diff();
  for (final c in (g['matrixInverse'] as List).cast<Map<String, dynamic>>()) {
    final m = CubismMatrix44();
    final src = (c['matrix'] as List);
    for (int i = 0; i < 16; i++) {
      m.array[i] = (src[i] as num).toDouble();
    }
    final inv = m.getInvert();
    final expected = (c['inverse'] as List).map((e) => (e as num).toDouble()).toList();
    for (int i = 0; i < 16; i++) {
      diff4.record(expected[i], inv.array[i], 'idx=$i');
    }
  }
  print('  matrixInverse: ${diff4.summary()}');

  // directionToRadian
  final diff5 = Diff();
  for (final c in (g['directionToRadian'] as List).cast<Map<String, dynamic>>()) {
    final from = CubismVector2(
        (c['fromX'] as num).toDouble(), (c['fromY'] as num).toDouble());
    final to = CubismVector2(
        (c['toX'] as num).toDouble(), (c['toY'] as num).toDouble());
    final expected = (c['result'] as num).toDouble();
    final actual = CubismMath.directionToRadian(from, to);
    diff5.record(expected, actual, '');
  }
  print('  directionToRadian: ${diff5.summary()}');
}

// ---------------------------------------------------------------------------
// BREATH
// ---------------------------------------------------------------------------
void verifyBreath() {
  _section('Breath sine wave (with Float32 truncation)');
  final g = _loadGolden('breath_golden.json');
  final offset = Float32.cast((g['offset'] as num).toDouble());
  final peak = Float32.cast((g['peak'] as num).toDouble());
  final cycle = Float32.cast((g['cycle'] as num).toDouble());

  final diff = Diff();
  double currentTime = 0.0;
  final dt = Float32.cast(1.0 / 60.0);
  final twoPi = Float32.cast(2.0 * CubismMath.pi);
  final frames = (g['frames'] as List).cast<Map<String, dynamic>>();
  for (int i = 0; i < frames.length; i++) {
    currentTime = Float32.cast(currentTime + dt);
    final t = Float32.cast(currentTime * twoPi);
    final s = LibM.sinf(Float32.cast(t / cycle));
    final actual = Float32.cast(offset + Float32.cast(peak * s));
    final expected = (frames[i]['value'] as num).toDouble();
    diff.record(expected, actual, 'frame=$i');
  }
  print('  ${diff.summary()}');
}

// ---------------------------------------------------------------------------
// LOOK
// ---------------------------------------------------------------------------
void verifyLook() {
  _section('Look formula (with Float32 truncation)');
  final g = _loadGolden('look_golden.json');
  final fX = Float32.cast((g['factorX'] as num).toDouble());
  final fY = Float32.cast((g['factorY'] as num).toDouble());
  final fXY = Float32.cast((g['factorXY'] as num).toDouble());

  final diff = Diff();
  for (final c in (g['inputs'] as List).cast<Map<String, dynamic>>()) {
    final dx = Float32.cast((c['dragX'] as num).toDouble());
    final dy = Float32.cast((c['dragY'] as num).toDouble());
    final expected = (c['delta'] as num).toDouble();
    // Match C++ float32 chain: each binop truncates to float32
    final dragXY = Float32.cast(dx * dy);
    final t1 = Float32.cast(fX * dx);
    final t2 = Float32.cast(fY * dy);
    final t3 = Float32.cast(fXY * dragXY);
    final actual = Float32.cast(Float32.cast(t1 + t2) + t3);
    diff.record(expected, actual, 'dx=$dx,dy=$dy');
  }
  print('  ${diff.summary()}');
}

// ---------------------------------------------------------------------------
// MODEL SETTINGS
// ---------------------------------------------------------------------------
void verifyModelSetting() {
  _section('CubismModelSettingJson');
  final g = _loadGolden('model_setting_haru_golden.json');
  final settings = CubismModelSettingJson.fromString(
      File('${Directory.current.path}/Samples/Resources/Haru/Haru.model3.json')
          .readAsStringSync());

  int matches = 0, mismatches = 0;
  void check(String name, dynamic expected, dynamic actual) {
    if (expected == actual) {
      matches++;
    } else {
      mismatches++;
      print('  MISMATCH: $name expected=$expected actual=$actual');
    }
  }

  check('modelFileName', g['modelFileName'], settings.modelFileName);
  check('textureCount', g['textureCount'], settings.textureCount);
  check('physicsFileName', g['physicsFileName'], settings.physicsFileName);
  check('poseFileName', g['poseFileName'], settings.poseFileName);
  check('expressionCount', g['expressionCount'], settings.expressionCount);
  check('motionGroupCount', g['motionGroupCount'], settings.motionGroupCount);
  check('hitAreasCount', g['hitAreasCount'], settings.hitAreasCount);
  check('eyeBlinkParameterCount', g['eyeBlinkParameterCount'],
      settings.eyeBlinkParameterCount);
  check('lipSyncParameterCount', g['lipSyncParameterCount'],
      settings.lipSyncParameterCount);

  for (final t in (g['textures'] as List).asMap().entries) {
    check('texture[${t.key}]', (t.value as Map)['file'],
        settings.getTextureFileName(t.key));
  }
  for (final e in (g['expressions'] as List).asMap().entries) {
    final exp = e.value as Map;
    check('expr[${e.key}].name', exp['name'], settings.getExpressionName(e.key));
    check('expr[${e.key}].file', exp['file'], settings.getExpressionFileName(e.key));
  }
  for (final mg in (g['motionGroups'] as List).asMap().entries) {
    final group = mg.value as Map;
    check('motionGroup[${mg.key}].name', group['name'],
        settings.getMotionGroupName(mg.key));
    check('motionGroup[${mg.key}].count', group['count'],
        settings.getMotionCount(group['name'] as String));
  }
  print('  matches=$matches mismatches=$mismatches');
}

// ---------------------------------------------------------------------------
// EXPRESSION (parity test using actual model)
// ---------------------------------------------------------------------------
void verifyExpression(CubismMoc moc) {
  _section('CubismExpressionMotion');
  final g = _loadGolden('expression_haru_F01_golden.json');
  final expression = CubismExpressionMotion.fromString(
      File('${Directory.current.path}/Samples/Resources/Haru/expressions/F01.exp3.json')
          .readAsStringSync());

  // Verify metadata matches
  print('  fadeInTime: dart=${expression.fadeInTime} cpp=${g['fadeInTime']}');
  print('  fadeOutTime: dart=${expression.fadeOutTime} cpp=${g['fadeOutTime']}');
  print('  parameter count: dart=${expression.parameters.length} cpp=${(g['expressionParameters'] as List).length}');

  // Verify per-weight parameter values
  final diff = Diff();
  final samples = (g['weightSamples'] as List).cast<Map<String, dynamic>>();
  for (final sample in samples) {
    final weight = (sample['weight'] as num).toDouble();
    final goldenParams = (sample['params'] as List).cast<Map<String, dynamic>>();

    final model = CubismModel.fromMoc(moc);
    for (final p in model.parameters) {
      p.value = p.defaultValue;
    }
    expression.applyParameters(model, weight);

    for (final gp in goldenParams) {
      final id = gp['id'] as String;
      final dartParam = model.getParameter(id);
      if (dartParam == null) continue;
      final expected = (gp['value'] as num).toDouble();
      diff.record(expected, dartParam.value, 'w=$weight $id');
    }
    model.dispose();
  }
  print('  per-weight values: ${diff.summary()}');
}

// ---------------------------------------------------------------------------
// MOTION (parity test using actual model)
// ---------------------------------------------------------------------------
void verifyMotion(CubismMoc moc) {
  _section('CubismMotion');
  final g = _loadGolden('motion_haru_idle_golden.json');
  final motion = CubismMotion.fromString(File(
          '${Directory.current.path}/Samples/Resources/Haru/motions/haru_g_idle.motion3.json')
      .readAsStringSync());

  print('  duration: dart=${motion.data.duration} cpp=${g['duration']}');
  print('  fps: dart=${motion.data.fps} cpp=${g['fps']}');

  // Replay the same scenario the C++ generator did:
  // Use a motion manager with no fade times for clean comparison
  motion.fadeInSeconds = 0.0;
  motion.fadeOutSeconds = 0.0;
  motion.isLoop = false;

  final model = CubismModel.fromMoc(moc);
  final manager = CubismMotionManager();
  manager.startMotionPriority(motion, priority: 1);

  final diff = Diff();
  final dt = 1.0 / 60.0;
  final frames = (g['frames'] as List).cast<Map<String, dynamic>>();

  for (int i = 0; i < frames.length; i++) {
    manager.updateMotion(model, dt);
    model.update();

    final samples = (frames[i]['paramSamples'] as List).cast<Map<String, dynamic>>();
    for (final sample in samples) {
      final id = sample['id'] as String;
      final expected = (sample['value'] as num).toDouble();
      final dartParam = model.getParameter(id);
      if (dartParam == null) continue;
      diff.record(expected, dartParam.value, 'frame=$i $id');
    }
  }
  print('  ${diff.summary()}');
  model.dispose();
}

// ---------------------------------------------------------------------------
// MOTION QUEUE (parity test)
// ---------------------------------------------------------------------------
void verifyMotionQueue(CubismMoc moc) {
  _section('CubismMotionQueue (priority transitions)');
  final g = _loadGolden('motion_queue_golden.json');
  final m1 = CubismMotion.fromString(File(
          '${Directory.current.path}/Samples/Resources/Haru/motions/haru_g_idle.motion3.json')
      .readAsStringSync());
  final m2 = CubismMotion.fromString(File(
          '${Directory.current.path}/Samples/Resources/Haru/motions/haru_g_m01.motion3.json')
      .readAsStringSync());
  m1.fadeInSeconds = 0.5;
  m1.fadeOutSeconds = 0.5;
  m2.fadeInSeconds = 0.5;
  m2.fadeOutSeconds = 0.5;

  final model = CubismModel.fromMoc(moc);
  final manager = CubismMotionManager();
  manager.startMotionPriority(m1, priority: 1);

  final diff = Diff();
  final dt = 1.0 / 60.0;
  final frames = (g['frames'] as List).cast<Map<String, dynamic>>();

  for (int i = 0; i < frames.length; i++) {
    if (i == 30) {
      manager.startMotionPriority(m2, priority: 2);
    }
    manager.updateMotion(model, dt);
    model.update();

    final samples = (frames[i]['paramSamples'] as List).cast<Map<String, dynamic>>();
    for (final sample in samples) {
      final id = sample['id'] as String;
      final expected = (sample['value'] as num).toDouble();
      final dartParam = model.getParameter(id);
      if (dartParam == null) continue;
      diff.record(expected, dartParam.value, 'frame=$i $id');
    }
  }
  print('  ${diff.summary()}');
  model.dispose();
}

// ---------------------------------------------------------------------------
// PHYSICS (parity test)
// ---------------------------------------------------------------------------
void verifyPhysics(CubismMoc moc) {
  _section('CubismPhysics (300-frame simulation)');
  final g = _loadGolden('physics_haru_golden.json');
  final physics = CubismPhysics.fromString(
      File('${Directory.current.path}/Samples/Resources/Haru/Haru.physics3.json')
          .readAsStringSync());

  final model = CubismModel.fromMoc(moc);
  physics.stabilization(model);

  final diff = Diff();
  final dt = 1.0 / 60.0;
  final frameData = (g['frameData'] as List).cast<Map<String, dynamic>>();

  // Match C++ generator's float32-truncated input chain:
  //   sin(i * 0.1f) * 30.0f
  // 0.1f and 30.0f are float32 constants in C++; the multiplication is in
  // float32 then promoted to double for sin().
  final f01 = Float32.cast(0.1);
  final f30 = Float32.cast(30.0);
  for (int i = 0; i < frameData.length; i++) {
    final paramAngleX = model.getParameter('ParamAngleX');
    if (paramAngleX != null) {
      // Match C++: i * 0.1f (float multiplication, then promote to double for sin)
      final ix = Float32.cast(i.toDouble() * f01);
      paramAngleX.value = Float32.cast(math.sin(ix) * f30);
    }
    physics.evaluate(model, dt);
    model.update();

    final samples = (frameData[i]['paramSamples'] as List).cast<Map<String, dynamic>>();
    for (final sample in samples) {
      final id = sample['id'] as String;
      final expected = (sample['value'] as num).toDouble();
      final dartParam = model.getParameter(id);
      if (dartParam == null) continue;
      diff.record(expected, dartParam.value, 'frame=$i $id');
    }
  }
  print('  ${diff.summary()}');
  model.dispose();
}

// ---------------------------------------------------------------------------
// POSE (parity test)
// ---------------------------------------------------------------------------
void verifyPose(CubismMoc moc) {
  _section('CubismPose (120-frame simulation)');
  final g = _loadGolden('pose_golden.json');
  final pose = CubismPose.fromString(
      File('${Directory.current.path}/Samples/Resources/Haru/Haru.pose3.json')
          .readAsStringSync());

  final model = CubismModel.fromMoc(moc);

  final diff = Diff();
  final dt = 1.0 / 60.0;
  final frames = (g['frames'] as List).cast<Map<String, dynamic>>();

  for (int i = 0; i < frames.length; i++) {
    pose.updateParameters(model, dt);
    model.update();

    final partOpacities = (frames[i]['partOpacities'] as List).cast<Map<String, dynamic>>();
    for (final po in partOpacities) {
      final id = po['id'] as String;
      final expected = (po['opacity'] as num).toDouble();
      final dartPart = model.getPart(id);
      if (dartPart == null) continue;
      diff.record(expected, dartPart.opacity, 'frame=$i $id');
    }
  }
  print('  ${diff.summary()}');
  model.dispose();
}

// ---------------------------------------------------------------------------
// MAIN
// ---------------------------------------------------------------------------
void main() {
  // Load Cubism Core library
  final coreSoPath =
      '${Directory.current.path}/Core/dll/linux/x86_64/libLive2DCubismCore.so';
  NativeLibrary.overrideBindings(
      CubismCoreBindings(DynamicLibrary.open(coreSoPath)));

  print('═══════════════════════════════════════════════════════════');
  print('  Cubism Framework Dart vs C++ Parity Verification');
  print('═══════════════════════════════════════════════════════════');
  print('Comparing Dart implementations against C++ golden reference data.');
  print('Threshold reporting:');
  print('  over1e-6: differences larger than 1 micro-unit (float vs double)');
  print('  over1e-4: differences larger than 0.0001 (significant)');
  print('  over1e-2: differences larger than 0.01 (visible)');

  verifyMath();
  verifyBreath();
  verifyLook();
  verifyModelSetting();

  // Model-based tests
  final moc = CubismMoc.fromBytes(
      File('${Directory.current.path}/Samples/Resources/Haru/Haru.moc3')
          .readAsBytesSync());

  verifyExpression(moc);
  verifyMotion(moc);
  verifyMotionQueue(moc);
  verifyPhysics(moc);
  verifyPose(moc);

  moc.dispose();
  print('');
  print('═══════════════════════════════════════════════════════════');
  print('  Verification complete');
  print('═══════════════════════════════════════════════════════════');
}
